### ISSUE TITLE
Do you have AIM dataset's links？I find it‘s hard to get its train datas.

### ISSUE THREAD

**Issue by Ulysiss** [CVMI-Lab/UHDM#10]
HELLO!Thank you for your work ,do you have AIM dataset's links？I find it‘s hard to get its train datas.

**Comment by XinYu-Andy** [comment]
> HELLO!Thank you for your work ,do you have AIM dataset's links？I find it‘s hard to get its train datas.

Please see this issue #9

**Comment by Ulysiss** [comment]
> > HELLO!Thank you for your work ,do you have AIM dataset's links？I find it‘s hard to get its train datas.
> 
> Please see this issue #9

Thank you for your kindly help!!!(*˘︶˘*).。.:*♡
