### ISSUE TITLE
Could you help split the test dataset?

### ISSUE THREAD

**Issue by Thothene** [CVMI-Lab/UHDM#11]
I encountered a problem while downloading the dataset. After checking the previous issues, I found that someone like me can download the fragmented training dataset but they cannot download the whole dataset. Because the test dataset is slightly large, I hope you can help to slice the test dataset, thank you!

**Comment by XinYu-Andy** [comment]
Hi, 
Sorry for the late reply, I have uploaded small files [here](https://drive.google.com/drive/folders/1GEuY4U3g_gBl3hsklQKaQa5aFZwRRmXl?usp=share_link).

> I encountered a problem while downloading the dataset. After checking the previous issues, I found that someone like me can download the fragmented training dataset but they cannot download the whole dataset. Because the test dataset is slightly large, I hope you can help to slice the test dataset, thank you!

**Comment by Thothene** [comment]
Thank you very much for your work, which has helped me a lot！
