### ISSUE TITLE
Resouce about LCDMoire dataset 

### ISSUE THREAD

**Issue by jason850124** [CVMI-Lab/UHDM#12]
Hi , authors , 

Would you mind provide the resource about the lcdmoire dataset  ? Through studied your paper , I'm really interested in this subject, and I  start to search all dataset about moire texture which you reminded and used in the paper ( I wanna train the ESDNet )  , I found all of them,but LCDMoire dataset, no matter what ,thanks for your rearch and resource, I learn a lot from this.

**Comment by XinYu-Andy** [comment]
> Hi , authors ,
> 
> Would you mind provide the resource about the lcdmoire dataset ? Through studied your paper , I'm really interested in this subject, and I start to search all dataset about moire texture which you reminded and used in the paper ( I wanna train the ESDNet ) , I found all of them,but LCDMoire dataset, no matter what ,thanks for your rearch and resource, I learn a lot from this.

Please refer to [this issue](https://github.com/CVMI-Lab/UHDM/issues/9#issue-1401973402)

**Comment by jason850124** [comment]
Ok , I'll check it late, thanks for replying !
