### ISSUE TITLE
The model web link has expired

### ISSUE THREAD

**Issue by xiaotianai** [CVMI-Lab/UHDM#13]
The model connection has expired, can you re-upload the pre-trained model

**Comment by XinYu-Andy** [comment]
> The model connection has expired, can you re-upload the pre-trained model

Hi,
I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive.
What's the error reported when you downloaded it?

**Comment by xiaotianai** [comment]
When I click on this link, an error will be reported







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CVMI-Lab/UHDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月1日(星期天) 凌晨2:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13)





  
The model connection has expired, can you re-upload the pre-trained model
  
Hi,
 I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive.
 What's the error reported when you downloaded it?

**Comment by xiaotianai** [comment]
When I use gdown to download, it will report such an error. I think it should be a problem that you don't have permission to open.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CVMI-Lab/UHDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月1日(星期天) 凌晨2:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13)





  
The model connection has expired, can you re-upload the pre-trained model
  
Hi,
 I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive.
 What's the error reported when you downloaded it?

**Comment by XinYu-Andy** [comment]
> When I use gdown to download, it will report such an error. I think it should be a problem that you don't have permission to open.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" ***@***.***&gt;; 发送时间:&nbsp;2023年1月1日(星期天) 凌晨2:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) The model connection has expired, can you re-upload the pre-trained model Hi, I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive. What's the error reported when you downloaded it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hi,
The problem seems to be from `gdown` side (see this [issue](https://github.com/wkentaro/gdown/issues/26)). At this moment, I suggest you firstly upgrade the gdown via :
`pip install --upgrade --no-cache-dir gdown`. 
If this cannot work, I suggest you download it directly from google drive. I will try to find a way to fix this problem.

**Comment by xiaotianai** [comment]
Thank you very much for your reply, I have solved the problem！！
Then, I have another question. You said in git that you only need 17ms to process a 4k image using a 3090 graphics card, but it takes me 8s under the same configuration. Moreover, if I process a 4000*8000 panorama, the memory will be exceeded. Have you MEET this problem, or do you have any better suggestions





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CVMI-Lab/UHDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13)





  
When I use gdown to download, it will report such an error. I think it should be a problem that you don't have permission to open.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月1日(星期天) 凌晨2:03 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) The model connection has expired, can you re-upload the pre-trained model Hi, I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive. What's the error reported when you downloaded it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Hi,
 The problem seems to be from gdown side (see this issue). At this moment, I suggest you firstly upgrade the gdown via :
 pip install --upgrade --no-cache-dir gdown.
 If this cannot work, I suggest you download it directly from google drive. I will try to find a way to fix this problem.

**Comment by XinYu-Andy** [comment]
> Thank you very much for your reply, I have solved the problem！！ Then, I have another question. You said in git that you only need 17ms to process a 4k image using a 3090 graphics card, but it takes me 8s under the same configuration. Moreover, if I process a 4000*8000 panorama, the memory will be exceeded. Have you MEET this problem, or do you have any better suggestions
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" ***@***.***&gt;; 发送时间:&nbsp;2023年1月3日(星期二) 中午1:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) When I use gdown to download, it will report such an error. I think it should be a problem that you don't have permission to open. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月1日(星期天) 凌晨2:03 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) The model connection has expired, can you re-upload the pre-trained model Hi, I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive. What's the error reported when you downloaded it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; Hi, The problem seems to be from gdown side (see this issue). At this moment, I suggest you firstly upgrade the gdown via : pip install --upgrade --no-cache-dir gdown. If this cannot work, I suggest you download it directly from google drive. I will try to find a way to fix this problem. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

No, I haven't meet this problem. How do you test it, through our code or other implementation?

**Comment by xiaotianai** [comment]
I run your demo_test.py this program




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CVMI-Lab/UHDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13)





  
Thank you very much for your reply, I have solved the problem！！ Then, I have another question. You said in git that you only need 17ms to process a 4k image using a 3090 graphics card, but it takes me 8s under the same configuration. Moreover, if I process a 40008000 panorama, the memory will be exceeded. Have you MEET this problem, or do you have any better suggestions
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月3日(星期二) 中午1:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) When I use gdown to download, it will report such an error. I think it should be a problem that you don't have permission to open. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月1日(星期天) 凌晨2:03 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) The model connection has expired, can you re-upload the pre-trained model Hi, I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive. What's the error reported when you downloaded it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, The problem seems to be from gdown side (see this issue). At this moment, I suggest you firstly upgrade the gdown via : pip install --upgrade --no-cache-dir gdown. If this cannot work, I suggest you download it directly from google drive. I will try to find a way to fix this problem. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.*&gt;
  
No, I haven't meet this problem. How do you test it, through our code or other implementation?

**Comment by XinYu-Andy** [comment]
> I run your demo_test.py this program
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" ***@***.***&gt;; 发送时间:&nbsp;2023年1月3日(星期二) 下午3:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) Thank you very much for your reply, I have solved the problem！！ Then, I have another question. You said in git that you only need 17ms to process a 4k image using a 3090 graphics card, but it takes me 8s under the same configuration. Moreover, if I process a 40008000 panorama, the memory will be exceeded. Have you MEET this problem, or do you have any better suggestions … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月3日(星期二) 中午1:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) When I use gdown to download, it will report such an error. I think it should be a problem that you don't have permission to open. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月1日(星期天) 凌晨2:03 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) The model connection has expired, can you re-upload the pre-trained model Hi, I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive. What's the error reported when you downloaded it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, The problem seems to be from gdown side (see this issue). At this moment, I suggest you firstly upgrade the gdown via : pip install --upgrade --no-cache-dir gdown. If this cannot work, I suggest you download it directly from google drive. I will try to find a way to fix this problem. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.*&gt; No, I haven't meet this problem. How do you test it, through our code or other implementation? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I guess you may just test one image and calculate the run time of the whole code processing, including model loading. We do statistics by testing 500 images and calculate the average time for model processing (see [here](https://github.com/CVMI-Lab/UHDM/blob/933241ac3bd96b84743b0effd520453ecaebd7cd/model/model.py#L37)).

**Comment by xiaotianai** [comment]
Thanks, I'm trying it out, thanks for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CVMI-Lab/UHDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13)





  
I run your demo_test.py this program
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月3日(星期二) 下午3:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) Thank you very much for your reply, I have solved the problem！！ Then, I have another question. You said in git that you only need 17ms to process a 4k image using a 3090 graphics card, but it takes me 8s under the same configuration. Moreover, if I process a 40008000 panorama, the memory will be exceeded. Have you MEET this problem, or do you have any better suggestions … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月3日(星期二) 中午1:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) When I use gdown to download, it will report such an error. I think it should be a problem that you don't have permission to open. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间:&nbsp;2023年1月1日(星期天) 凌晨2:03 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) The model connection has expired, can you re-upload the pre-trained model Hi, I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive. What's the error reported when you downloaded it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Hi, The problem seems to be from gdown side (see this issue). At this moment, I suggest you firstly upgrade the gdown via : pip install --upgrade --no-cache-dir gdown. If this cannot work, I suggest you download it directly from google drive. I will try to find a way to fix this problem. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; No, I haven't meet this problem. How do you test it, through our code or other implementation? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.**&gt;
  
I guess you may just test one image and calculate the run time of the whole code processing, including model loading. We do statistics by testing 500 images and calculate the average time for model processing (see here).

**Comment by xiaotianai** [comment]
Hello, I am encountering this problem now. After the moiré removal operation, the color of the picture will change. What do you think is the cause of this problem?





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "CVMI-Lab/UHDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13)





  
When I use gdown to download, it will report such an error. I think it should be a problem that you don't have permission to open.
 …
 ------------------ 原始邮件 ------------------ 发件人: "CVMI-Lab/UHDM" @.&gt;; 发送时间: 2023年1月1日(星期天) 凌晨2:03 @.&gt;; @.@.&gt;; 主题: Re: [CVMI-Lab/UHDM] The model web link has expired (Issue #13) The model connection has expired, can you re-upload the pre-trained model Hi, I have checked the checkpoint just now and found I can still download it via "gdown" in the bash script or mannully downloading from google drive. What's the error reported when you downloaded it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Hi,
 The problem seems to be from gdown side (see this issue). At this moment, I suggest you firstly upgrade the gdown via :
 pip install --upgrade --no-cache-dir gdown.
 If this cannot work, I suggest you download it directly from google drive. I will try to find a way to fix this problem.

**Comment by XinYu-Andy** [comment]
It is caused by the inconsistent color style in training pairs. For moire images, it contains not only moire artifact but also degraded color style. So the model has also learnt to modify the color style.
