### ISSUE TITLE
Source code or reproduction code of DMCNN,MBCNN and MDDM models

### ISSUE THREAD

**Issue by Thothene** [CVMI-Lab/UHDM#14]
Hello！
I recently wanted to retrain other demoir´eing models, but found that DMCNN did not give the source code but only the code that others reproduced, while MBCNN and MDDM only had the test code. Would you like to ask if you have their source code or just retrained the model based on their test code?
Thank you!
DMCNN is from Moir´e photo restoration using multiresolution convolutional neural networks.
MBCNN is from Image demoireing with learnable bandpass filters.
MDDM is from Multi-scale Dynamic Feature Encoding Network for Image Demoireing.

**Comment by XinYu-Andy** [comment]
> Hello！ I recently wanted to retrain other demoir´eing models, but found that DMCNN did not give the source code but only the code that others reproduced, while MBCNN and MDDM only had the test code. Would you like to ask if you have their source code or just retrained the model based on their test code? Thank you! DMCNN is from Moir´e photo restoration using multiresolution convolutional neural networks. MBCNN is from Image demoireing with learnable bandpass filters. MDDM is from Multi-scale Dynamic Feature Encoding Network for Image Demoireing.

For MBCNN, we followed its official TensorFlow code and reproduced it using PyTorch.
For DMCNN, we modified (solve some bug) the unofficial code and retrained it.
For MDDM, we used the official code and retrained it.

**Comment by Thothene** [comment]
Thanks a lot，I will try later based on the help you provide.
