### ISSUE TITLE
WS-ESDNet : Any code for ws-esdnet

### ISSUE THREAD

**Issue by shubhoppo** [CVMI-Lab/UHDM#17]
Please suggest or upload the code, which shares the learnable parameters among the three branches.

**Comment by XinYu-Andy** [comment]
Hi,
You can just initialize one block [here](https://github.com/CVMI-Lab/UHDM/blob/99771dc6fc6bdee75bbee1cc5346428526c509f9/model/nets.py#L166) and re-use it in the forward.

> Please suggest or upload the code, which shares the learnable parameters among the three branches.

**Comment by shubhoppo** [comment]
Thanks for the suggestion. Could we expect using 2 SAM block(ESDNET-L) in weight shared manner give better PSNR than ESDNET?

**Comment by XinYu-Andy** [comment]
> Thanks for the suggestion. Could we expect using 2 SAM block(ESDNET-L) in weight shared manner give better PSNR than ESDNET?
It's possible, but I can't give you a definite answer. You may need to try it yourself.

**Comment by XinYu-Andy** [comment]
> Thanks for the suggestion. Could we expect using 2 SAM block(ESDNET-L) in weight shared manner give better PSNR than ESDNET?

It's possible, but I can't give you a definite answer. You may need to try it yourself.

**Comment by shubhoppo** [comment]
Also after weight sharing model size is compressed but inference time is still same.

**Comment by XinYu-Andy** [comment]
> Also after weight sharing model size is compressed but inference time is still same.

This is an expected behavior since parameter sharing does not reduce computational complexity.

**Comment by shubhoppo** [comment]
Yeah, Got it. Thanks
