### ISSUE TITLE
Training time & Nums of GPUs used

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [CVMI-Lab/UHDM#22]
Hi!
Wondering the traing time for UHDM and TIP 2018 dataset, since in the paper it was mentioned that only a single 3090 GPU was used for training?

Or, I misunderstood the paper's statement. How many 3090s were used for training?

Thanks a lot.

**Comment by XinYu-Andy** [comment]
> Hi! Wondering the traing time for UHDM and TIP 2018 dataset, since in the paper it was mentioned that only a single 3090 GPU was used for training?
> 
> Or, I misunderstood the paper's statement. How many 3090s were used for training?
> 
> Thanks a lot.

We only use one GPU for both training and inference. You can find the detailed training configuration in our papers.
