### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by XiaoHaoPan** [CVMI-Lab/UHDM#23]
The download of the training dataset in the network disk is incorrectly decompressed, and it cannot be decompressed after two consecutive times.

**Comment by tju-chengyijia** [comment]
I can't decompress it either, have you solved it?

**Comment by tju-chengyijia** [comment]
> The download of the training dataset in the network disk is incorrectly decompressed, and it cannot be decompressed after two consecutive times.

I can't decompress it either, have you solved it?

**Comment by XinYu-Andy** [comment]
Please see this [issue](https://github.com/CVMI-Lab/UHDM/issues/15#issue-1579986012)
