### ISSUE TITLE
need onnx model

### ISSUE THREAD

**Issue by weixia1** [CVMI-Lab/UHDM#4]
hi, i tried to transform the `.pth` model you [offered](https://drive.google.com/drive/folders/1DyA84UqM7zf3CeoEBNmTi_dJ649x2e7e)  into `.onnx` model, but the test result is bad. so，if can you offer a `.onnx` model or pth2onnx.py? thank you

**Comment by XinYu-Andy** [comment]
Sorry, I do not have the experience working on .onnx model and we have no plan to do this.

> hi, i tried to transform the `.pth` model you [offered](https://drive.google.com/drive/folders/1DyA84UqM7zf3CeoEBNmTi_dJ649x2e7e) into `.onnx` model, but the test result is bad. so，if can you offer a `.onnx` model or pth2onnx.py? thank you

**Comment by weixia1** [comment]
ok

**Comment by weixia1** [comment]
i have solved it， so  happy!

> hi, i tried to transform the `.pth` model you [offered](https://drive.google.com/drive/folders/1DyA84UqM7zf3CeoEBNmTi_dJ649x2e7e) into `.onnx` model, but the test result is bad. so，if can you offer a `.onnx` model or pth2onnx.py? thank you

**Comment by weixia1** [comment]
I have solved this problem to get correct result, so happy!



> hi, i tried to transform the `.pth` model you [offered](https://drive.google.com/drive/folders/1DyA84UqM7zf3CeoEBNmTi_dJ649x2e7e) into `.onnx` model, but the test result is bad. so，if can you offer a `.onnx` model or pth2onnx.py? thank you

**Comment by XinYu-Andy** [comment]
> I have solved this problem to get correct result, so happy!
> 
> > hi, i tried to transform the `.pth` model you [offered](https://drive.google.com/drive/folders/1DyA84UqM7zf3CeoEBNmTi_dJ649x2e7e) into `.onnx` model, but the test result is bad. so，if can you offer a `.onnx` model or pth2onnx.py? thank you

congrats!

**Comment by CVmeta** [comment]
> I have solved this problem to get correct result, so happy!
> 
> > hi, i tried to transform the `.pth` model you [offered](https://drive.google.com/drive/folders/1DyA84UqM7zf3CeoEBNmTi_dJ649x2e7e) into `.onnx` model, but the test result is bad. so，if can you offer a `.onnx` model or pth2onnx.py? thank you

Seem problem, could you please share your solution or .onnx model？tks

**Comment by home56200** [comment]
Can you provide Onnx program code, please, thank you
