### ISSUE TITLE
Have you tested how much video memory will be used when using the GPU?

### ISSUE THREAD

**Issue by 1362802590** [CVMI-Lab/UHDM#6]
HI,Have you tested how much video memory will be used when using the GPU?

**Comment by XinYu-Andy** [comment]
What do you mean video?

> HI,Have you tested how much video memory will be used when using the GPU?

**Comment by 1362802590** [comment]
video memory 显存

**Comment by XinYu-Andy** [comment]
I remember it would cost around 9000MiB GPU memory when testing a 4K image. As for the training, around 11000MiB for 2 batch_size * (768,768,3) resolution image. 
Not sure for this, just a rough estimation.

**Comment by 1362802590** [comment]
ok,thanks
