### ISSUE TITLE
How does it compare to this project(VideoDemoireing),

### ISSUE THREAD

**Issue by zhanghongyong123456** [CVMI-Lab/UHDM#7]
1. i test  my pic   by  https://github.com/CVMI-Lab/VideoDemoireing
I  test  my pic  ,The results are very poor.
![image](https://user-images.githubusercontent.com/48466610/191695332-44919893-84ab-4c23-a8be-9b312d03bc3e.png)
![image](https://user-images.githubusercontent.com/48466610/191697534-508a4ddb-ae54-413d-ae81-66f35f6ee683.png)

2. this pro compare with VideoDemoireing ,what is the difference?  1.  quality?  2. One（VideoDemoireing） for video and one（this project） for pictures?， i see   you  promat：
![image](https://user-images.githubusercontent.com/48466610/191697065-cc097b2c-eede-48c5-895c-57f46843ed7e.png)

**Comment by XinYu-Andy** [comment]
> 1. i test  my pic   by  https://github.com/CVMI-Lab/VideoDemoireing
>    I  test  my pic  ,The results are very poor.
>    ![image](https://user-images.githubusercontent.com/48466610/191695332-44919893-84ab-4c23-a8be-9b312d03bc3e.png)
>    ![image](https://user-images.githubusercontent.com/48466610/191697534-508a4ddb-ae54-413d-ae81-66f35f6ee683.png)
> 2. this pro compare with VideoDemoireing ,what is the difference?  1.  quality?  2. One（VideoDemoireing） for video and one（this project） for pictures?， i see   you  promat：
>    ![image](https://user-images.githubusercontent.com/48466610/191697065-cc097b2c-eede-48c5-895c-57f46843ed7e.png)

Hi,

The network of video demoireing is different with this repo. You could try this repo for image demoireing. The key in video demoireing is the relation-based loss to solve the temporary consistency.

**Comment by zhanghongyong123456** [comment]
> > 1. i test  my pic   by  https://github.com/CVMI-Lab/VideoDemoireing
> >    I  test  my pic  ,The results are very poor.
> >    ![image](https://user-images.githubusercontent.com/48466610/191695332-44919893-84ab-4c23-a8be-9b312d03bc3e.png)
> >    ![image](https://user-images.githubusercontent.com/48466610/191697534-508a4ddb-ae54-413d-ae81-66f35f6ee683.png)
> > 2. this pro compare with VideoDemoireing ,what is the difference?  1.  quality?  2. One（VideoDemoireing） for video and one（this project） for pictures?， i see   you  promat：
> >    ![image](https://user-images.githubusercontent.com/48466610/191697065-cc097b2c-eede-48c5-895c-57f46843ed7e.png)
> 
> Hi,
> 
> The network of video demoireing is different with this repo. You could try this repo for image demoireing. The key in video demoireing is the relation-based loss to solve the temporary consistency.

I find  this project  have  60fps  4K on 3090, That's consistent with the video stream removal morire pattern,but  (VideoDemoireing  pro )The effect is worse than this project. What should I do

**Comment by XinYu-Andy** [comment]
> > > 1. i test  my pic   by  https://github.com/CVMI-Lab/VideoDemoireing
> > >    I  test  my pic  ,The results are very poor.
> > >    ![image](https://user-images.githubusercontent.com/48466610/191695332-44919893-84ab-4c23-a8be-9b312d03bc3e.png)
> > >    ![image](https://user-images.githubusercontent.com/48466610/191697534-508a4ddb-ae54-413d-ae81-66f35f6ee683.png)
> > > 2. this pro compare with VideoDemoireing ,what is the difference?  1.  quality?  2. One（VideoDemoireing） for video and one（this project） for pictures?， i see   you  promat：
> > >    ![image](https://user-images.githubusercontent.com/48466610/191697065-cc097b2c-eede-48c5-895c-57f46843ed7e.png)
> > 
> > 
> > Hi,
> > The network of video demoireing is different with this repo. You could try this repo for image demoireing. The key in video demoireing is the relation-based loss to solve the temporary consistency.
> 
> I find this project have 60fps 4K on 3090, That's consistent with the video stream removal morire pattern,but (VideoDemoireing pro )The effect is worse than this project. What should I do, for VideoDemoireing pro 4K 60fps? Looks like a small resolution

I think this is a future work, i.e., video demoireing on 4K resolution. The key problem is there not exists a 4K moire-video dataset for training currently, or we can combine our image demoireing framework and relation-based loss to train the desired model.
